<?php

define('TM_MEMBER_BASE_INFO','TM_CACHE_MEMBER_00001');
define('TM_MEMBER_THIRDPARTY_LIST','TM_CACHE_MEMBER_00002');
define('TM_MEMBER_MEMBER_ID','TM_CACHE_MEMBER_00003');

define('TM_MEMBER_WEATHER_INFO','TM_CACHE_MEMBER_00004');
define('TM_MEMBER_CALENDAR_INFO','TM_CACHE_MEMBER_00005');
